// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA90TqeT_zG_2PTgW6TEvP2nmRLGIrDd0w',
    appId: '1:968115587616:web:bf05947d81cc60dd41ca45',
    messagingSenderId: '968115587616',
    projectId: 'school-bus-97c6c',
    authDomain: 'school-bus-97c6c.firebaseapp.com',
    storageBucket: 'school-bus-97c6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgbIY1Sp9Fozc8kBA3n7ch7WWF3XuncA8',
    appId: '1:968115587616:android:6dd8655a672eca3f41ca45',
    messagingSenderId: '968115587616',
    projectId: 'school-bus-97c6c',
    storageBucket: 'school-bus-97c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Qq7ZsUAKs-XqHGcGbsCUvi6hB_1HlAc',
    appId: '1:968115587616:ios:86efbedf113317be41ca45',
    messagingSenderId: '968115587616',
    projectId: 'school-bus-97c6c',
    storageBucket: 'school-bus-97c6c.firebasestorage.app',
    androidClientId: '968115587616-e4o89qm9rm3jpotbkderigdt4hprjnql.apps.googleusercontent.com',
    iosClientId: '968115587616-glin51m8ogi8k7hpgcoibfd5t1t38m79.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolBus',
  );
}
